[package]
name = "topus"
version = "0.1.7"
edition = "2021"

authors = ["techrust <ziranjuangu@outlook.com>"]
description = "Write HTML in Rust."
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
